version: '3'
services:
  python_ocr:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/src
    stdin_open: true # permet de le lancer en detach mode et d'aller dedans si nécessaire
    tty: true #
